CREATE TABLE IF NOT EXISTS public.buffet_options (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10, 2) not null,
  is_available boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
ALTER TABLE public.buffet_options ENABLE ROW LEVEL SECURITY;

-- Create Policies
-- 1. Allow everyone to read buffet options (needed for booking form)
CREATE POLICY "Allow public read access"
  ON public.buffet_options FOR SELECT
  USING (true);

-- 2. Allow authenticated users (staff/admins) to insert, update, delete
-- Note: checking role in a real app should be stricter (e.g. auth.jwt() ->> 'role' = 'admin')
-- but for this template 'authenticated' matches the existing pattern.
CREATE POLICY "Allow admin write access"
  ON public.buffet_options FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Insert Default Buffet Options
INSERT INTO public.buffet_options (name, description, price, is_available)
SELECT 'Standard Continental', 'Coffee, Tea, Pastries', 15.00, true
WHERE NOT EXISTS (SELECT 1 FROM public.buffet_options WHERE name = 'Standard Continental');

INSERT INTO public.buffet_options (name, description, price, is_available)
SELECT 'Business Lunch', 'Salads, Main Course, Dessert', 35.00, true
WHERE NOT EXISTS (SELECT 1 FROM public.buffet_options WHERE name = 'Business Lunch');

INSERT INTO public.buffet_options (name, description, price, is_available)
SELECT 'Premium Package', 'Full Breakfast/Lunch with Drinks', 55.00, true
WHERE NOT EXISTS (SELECT 1 FROM public.buffet_options WHERE name = 'Premium Package');

INSERT INTO public.buffet_options (name, description, price, is_available)
SELECT 'Cocktail Reception', 'Appetizers, Drinks, Dessert', 45.00, true
WHERE NOT EXISTS (SELECT 1 FROM public.buffet_options WHERE name = 'Cocktail Reception');

INSERT INTO public.buffet_options (name, description, price, is_available)
SELECT 'Custom Menu', 'To Be Discussed', 0.00, true
WHERE NOT EXISTS (SELECT 1 FROM public.buffet_options WHERE name = 'Custom Menu');



