create table public.buffet_options (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10, 2) not null,
  is_available boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies
alter table public.buffet_options enable row level security;

create policy "Allow public read access"
  on public.buffet_options for select
  using (true);

create policy "Allow admin write access"
  on public.buffet_options for all
  using (auth.role() = 'authenticated'); -- Ideally restrict to admin role, but for now authenticated is a good start or check specific role if possible in policy

