-- Create restaurants table to store restaurant information
CREATE TABLE public.restaurants (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  type text NOT NULL,
  cuisine text NOT NULL,
  location text NOT NULL,
  description text,
  price_range text NOT NULL DEFAULT '$$',
  specialties text[] DEFAULT '{}',
  rating numeric(2,1) DEFAULT 4.0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Create restaurant_reviews table for user reviews
CREATE TABLE public.restaurant_reviews (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  restaurant_id integer NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  UNIQUE(restaurant_id, user_id)
);

-- Enable RLS
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurant_reviews ENABLE ROW LEVEL SECURITY;

-- Restaurant policies
CREATE POLICY "Everyone can view restaurants" 
ON public.restaurants 
FOR SELECT 
USING (true);

CREATE POLICY "RestaurantLead can manage restaurants" 
ON public.restaurants 
FOR ALL 
USING (get_current_user_role() = ANY (ARRAY['Admin'::app_role, 'RestaurantLead'::app_role]));

-- Restaurant reviews policies
CREATE POLICY "Everyone can view restaurant reviews" 
ON public.restaurant_reviews 
FOR SELECT 
USING (true);

CREATE POLICY "Authenticated users can create reviews" 
ON public.restaurant_reviews 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own reviews" 
ON public.restaurant_reviews 
FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own reviews" 
ON public.restaurant_reviews 
FOR DELETE 
USING (auth.uid() = user_id);

-- Insert sample restaurant data
INSERT INTO public.restaurants (name, type, cuisine, location, description, price_range, specialties, rating) VALUES
('The Grand Terrace', 'Fine Dining', 'Contemporary International', 'Main Floor', 'An elegant dining experience featuring globally-inspired cuisine with locally sourced ingredients.', '$$$', ARRAY['Wagyu Beef', 'Fresh Seafood', 'Seasonal Menu', 'Wine Pairing'], 5.0),
('Sunrise Café', 'Casual Dining', 'American & Continental', 'Garden Level', 'Start your day with freshly prepared breakfast and light lunch options in a relaxed atmosphere.', '$$', ARRAY['Fresh Pastries', 'Artisan Coffee', 'Healthy Options', 'Local Favorites'], 4.0),
('The Lounge Bar', 'Bar & Lounge', 'Cocktails & Small Plates', 'Rooftop', 'Sophisticated cocktails and tapas with panoramic city views in an intimate setting.', '$$', ARRAY['Craft Cocktails', 'Premium Spirits', 'Tapas', 'City Views'], 5.0),
('Pool Deck Grill', 'Outdoor Dining', 'Grilled Specialties', 'Pool Deck', 'Casual poolside dining featuring grilled favorites and refreshing beverages.', '$$', ARRAY['BBQ Classics', 'Fresh Salads', 'Tropical Drinks', 'Light Bites'], 4.0);

-- Create triggers for updated_at columns
CREATE TRIGGER update_restaurants_updated_at
  BEFORE UPDATE ON public.restaurants
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_restaurant_reviews_updated_at
  BEFORE UPDATE ON public.restaurant_reviews
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();