-- Add restaurant_id to menu_items to link dishes to specific restaurants
ALTER TABLE public.menu_items 
ADD COLUMN restaurant_id integer REFERENCES public.restaurants(id) ON DELETE CASCADE;

-- Create tables table for restaurant table management
CREATE TABLE public.restaurant_tables (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id integer NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  table_number text NOT NULL,
  capacity integer NOT NULL DEFAULT 4,
  status text NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'occupied', 'reserved', 'maintenance')),
  location_description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  UNIQUE(restaurant_id, table_number)
);

-- Create dining_reservations table for table/delivery bookings
CREATE TABLE public.dining_reservations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  restaurant_id integer NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  reservation_date date NOT NULL,
  reservation_time time NOT NULL,
  party_size integer NOT NULL,
  delivery_type text NOT NULL CHECK (delivery_type IN ('table', 'address')) DEFAULT 'table',
  table_id integer REFERENCES public.restaurant_tables(id) ON DELETE SET NULL,
  delivery_address text,
  delivery_fee numeric DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  special_requests text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled', 'completed')),
  guest_name text NOT NULL,
  guest_email text NOT NULL,
  guest_phone text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.restaurant_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dining_reservations ENABLE ROW LEVEL SECURITY;

-- Restaurant tables policies
CREATE POLICY "Everyone can view restaurant tables" 
ON public.restaurant_tables 
FOR SELECT 
USING (true);

CREATE POLICY "RestaurantLead can manage restaurant tables" 
ON public.restaurant_tables 
FOR ALL 
USING (get_current_user_role() = ANY (ARRAY['Admin'::app_role, 'RestaurantLead'::app_role]));

-- Dining reservations policies
CREATE POLICY "Users can create dining reservations" 
ON public.dining_reservations 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own dining reservations" 
ON public.dining_reservations 
FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Staff can view all dining reservations" 
ON public.dining_reservations 
FOR SELECT 
USING (get_current_user_role() = ANY (ARRAY['Admin'::app_role, 'RestaurantLead'::app_role, 'Receptionist'::app_role]));

CREATE POLICY "Staff can manage dining reservations" 
ON public.dining_reservations 
FOR ALL 
USING (get_current_user_role() = ANY (ARRAY['Admin'::app_role, 'RestaurantLead'::app_role, 'Receptionist'::app_role]));

-- Add triggers for updated_at columns
CREATE TRIGGER update_restaurant_tables_updated_at
  BEFORE UPDATE ON public.restaurant_tables
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_dining_reservations_updated_at
  BEFORE UPDATE ON public.dining_reservations
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Insert sample menu items for each restaurant
INSERT INTO public.menu_items (name, description, price, category, restaurant_id) VALUES
-- The Grand Terrace menu
('Wagyu Beef Tenderloin', 'Premium wagyu beef with seasonal vegetables and red wine reduction', 85.00, 'Main Course', 1),
('Pan-Seared Atlantic Salmon', 'Fresh salmon with lemon herb butter and roasted asparagus', 42.00, 'Main Course', 1),
('Truffle Risotto', 'Creamy arborio rice with black truffle and parmesan', 38.00, 'Main Course', 1),
('Chocolate Soufflé', 'Warm chocolate soufflé with vanilla ice cream', 18.00, 'Dessert', 1),

-- Sunrise Café menu
('Classic Breakfast', 'Two eggs, bacon, toast, and fresh fruit', 16.00, 'Breakfast', 2),
('Avocado Toast', 'Multigrain bread with smashed avocado and poached egg', 14.00, 'Breakfast', 2),
('Caesar Salad', 'Crisp romaine lettuce with parmesan and house-made dressing', 12.00, 'Lunch', 2),
('Fresh Smoothie Bowl', 'Açaí bowl with fresh berries and granola', 11.00, 'Breakfast', 2),

-- The Lounge Bar menu
('Signature Cocktail', 'House special with premium spirits', 18.00, 'Beverages', 3),
('Truffle Flatbread', 'Artisan flatbread with truffle oil and wild mushrooms', 22.00, 'Appetizers', 3),
('Charcuterie Board', 'Selection of cured meats, cheeses, and accompaniments', 28.00, 'Appetizers', 3),
('Dark Chocolate Tart', 'Rich chocolate tart with sea salt caramel', 14.00, 'Dessert', 3),

-- Pool Deck Grill menu
('BBQ Burger', 'Grilled beef patty with bacon and house sauce', 19.00, 'Main Course', 4),
('Grilled Chicken Salad', 'Fresh greens with grilled chicken and vinaigrette', 16.00, 'Salads', 4),
('Fish Tacos', 'Fresh fish with cabbage slaw and lime crema', 17.00, 'Main Course', 4),
('Tropical Smoothie', 'Mango, pineapple, and coconut blend', 8.00, 'Beverages', 4);

-- Insert sample restaurant tables
INSERT INTO public.restaurant_tables (restaurant_id, table_number, capacity, location_description) VALUES
-- The Grand Terrace tables
(1, 'T1', 2, 'Window table with city view'),
(1, 'T2', 4, 'Center dining area'),
(1, 'T3', 6, 'Private corner table'),
(1, 'T4', 4, 'Garden view table'),
(1, 'T5', 8, 'Large table for groups'),

-- Sunrise Café tables
(2, 'C1', 2, 'Cozy corner booth'),
(2, 'C2', 4, 'Garden level terrace'),
(2, 'C3', 2, 'Counter seating'),
(2, 'C4', 6, 'Family table'),

-- The Lounge Bar tables
(3, 'L1', 4, 'Rooftop with city panorama'),
(3, 'L2', 2, 'Intimate corner seating'),
(3, 'L3', 6, 'Bar counter'),
(3, 'L4', 4, 'Outdoor terrace'),

-- Pool Deck Grill tables
(4, 'P1', 4, 'Poolside table'),
(4, 'P2', 6, 'Deck seating with pool view'),
(4, 'P3', 2, 'Cabana table'),
(4, 'P4', 8, 'Large group table');