-- Add translations for About Us page and Footer
INSERT INTO translations (language, key, value) VALUES
-- About Us page translations
('fr', 'about_us', 'À propos'),
('en', 'about_us', 'About Us'),
('fr', 'about_us_subtitle', 'Découvrez notre histoire'),
('en', 'about_us_subtitle', 'Discover Our Story'),
('fr', 'our_story', 'Notre histoire'),
('en', 'our_story', 'Our Story'),
('fr', 'our_mission', 'Notre mission'),
('en', 'our_mission', 'Our Mission'),
('fr', 'our_vision', 'Notre vision'),
('en', 'our_vision', 'Our Vision'),
('fr', 'our_values', 'Nos valeurs fondamentales'),
('en', 'our_values', 'Our Core Values'),
('fr', 'default_story', 'Bienvenue dans notre établissement, où l''hospitalité rencontre l''excellence. Nous nous engageons à fournir un service exceptionnel et des expériences inoubliables à tous nos clients.'),
('en', 'default_story', 'Welcome to our establishment, where hospitality meets excellence. We are committed to providing exceptional service and unforgettable experiences for all our guests.'),
('fr', 'default_mission', 'Fournir des services d''hospitalité exceptionnels qui créent des expériences mémorables pour nos clients tout en maintenant les plus hauts standards de qualité et de service.'),
('en', 'default_mission', 'To provide exceptional hospitality services that create memorable experiences for our guests while maintaining the highest standards of quality and service.'),
('fr', 'default_vision', 'Être reconnu comme une destination de premier plan pour l''excellence en hospitalité, établissant de nouveaux standards en satisfaction client et qualité de service.'),
('en', 'default_vision', 'To be recognized as a premier destination for hospitality excellence, setting new standards in guest satisfaction and service quality.'),
('fr', 'excellence', 'Excellence'),
('en', 'excellence', 'Excellence'),
('fr', 'integrity', 'Intégrité'),
('en', 'integrity', 'Integrity'),
('fr', 'innovation', 'Innovation'),
('en', 'innovation', 'Innovation'),
('fr', 'service', 'Service'),
('en', 'service', 'Service'),
('fr', 'ready_experience_excellence', 'Prêt à vivre l''excellence ?'),
('en', 'ready_experience_excellence', 'Ready to Experience Excellence?'),
('fr', 'unforgettable_stay_description', 'Rejoignez-nous pour un séjour inoubliable où chaque détail est conçu pour dépasser vos attentes.'),
('en', 'unforgettable_stay_description', 'Join us for an unforgettable stay where every detail is crafted to exceed your expectations.'),
('fr', 'book_your_stay', 'Réservez votre séjour'),
('en', 'book_your_stay', 'Book Your Stay'),
('fr', 'contact_us', 'Contactez-nous'),
('en', 'contact_us', 'Contact Us'),
('fr', 'content_not_available', 'Contenu non disponible'),
('en', 'content_not_available', 'Content Not Available'),
('fr', 'content_load_error', 'Impossible de charger le contenu de la page. Veuillez réessayer plus tard.'),
('en', 'content_load_error', 'Unable to load page content. Please try again later.'),
('fr', 'about_image_alt', 'Image à propos de nous'),
('en', 'about_image_alt', 'About us image'),

-- Footer translations
('fr', 'company_name', 'Kabinda Lodge'),
('en', 'company_name', 'Kabinda Lodge'),
('fr', 'premium_hospitality', 'Hospitalité Premium'),
('en', 'premium_hospitality', 'Premium Hospitality'),
('fr', 'footer_description', 'Découvrez un luxe et un confort inégalés au Kabinda Lodge, où chaque détail est conçu pour créer des souvenirs inoubliables.'),
('en', 'footer_description', 'Experience unparalleled luxury and comfort at Kabinda Lodge, where every detail is crafted to create unforgettable memories.'),
('fr', 'quick_links', 'Liens rapides'),
('en', 'quick_links', 'Quick Links'),
('fr', 'rooms_suites', 'Chambres et suites'),
('en', 'rooms_suites', 'Rooms & Suites'),
('fr', 'restaurant', 'Restaurant'),
('en', 'restaurant', 'Restaurant'),
('fr', 'contact', 'Contact'),
('en', 'contact', 'Contact'),
('fr', 'services', 'Services'),
('en', 'services', 'Services'),
('fr', 'concierge', 'Conciergerie'),
('en', 'concierge', 'Concierge'),
('fr', 'spa_wellness', 'Spa et bien-être'),
('en', 'spa_wellness', 'Spa & Wellness'),
('fr', 'transportation', 'Transport'),
('en', 'transportation', 'Transportation'),
('fr', 'special_occasions', 'Occasions spéciales'),
('en', 'special_occasions', 'Special Occasions'),
('fr', 'default_address', '123 Lodge Road, Kabinda City'),
('en', 'default_address', '123 Lodge Road, Kabinda City'),
('fr', 'default_phone', '+1 (555) 123-4567'),
('en', 'default_phone', '+1 (555) 123-4567'),
('fr', 'default_email', 'info@kakindalodge.com'),
('en', 'default_email', 'info@kakindalodge.com'),
('fr', 'all_rights_reserved', 'Tous droits réservés.'),
('en', 'all_rights_reserved', 'All rights reserved.'),
('fr', 'privacy_policy', 'Politique de confidentialité'),
('en', 'privacy_policy', 'Privacy Policy'),
('fr', 'terms_of_service', 'Conditions d''utilisation'),
('en', 'terms_of_service', 'Terms of Service')

ON CONFLICT (language, key) DO UPDATE SET 
value = EXCLUDED.value,
updated_at = now();