-- Add missing translations that are commonly used across the application
INSERT INTO translations (language, key, value) VALUES
-- Navigation and common buttons
('fr', 'view_details', 'Voir les détails'),
('en', 'view_details', 'View Details'),
('fr', 'back_to_home', 'Retour à l''accueil'),
('en', 'back_to_home', 'Back to Home'),
('fr', 'explore_rooms', 'Explorer les chambres'),
('en', 'explore_rooms', 'Explore Rooms'),
('fr', 'guest_login', 'Connexion client'),
('en', 'guest_login', 'Guest Login'),
('fr', 'browse_rooms', 'Parcourir les chambres'),
('en', 'browse_rooms', 'Browse Rooms'),
('fr', 'book_now', 'Réserver maintenant'),
('en', 'book_now', 'Book Now'),

-- Home page content
('fr', 'premium_amenities', 'Équipements et services haut de gamme'),
('en', 'premium_amenities', 'Premium Amenities & Services'),
('fr', 'amenities_description', 'Découvrez des installations de classe mondiale et un service personnalisé conçu pour dépasser vos attentes'),
('en', 'amenities_description', 'Experience world-class facilities and personalized service designed to exceed your expectations'),
('fr', 'luxury_accommodation', 'Hébergement de luxe'),
('en', 'luxury_accommodation', 'Luxury Accommodation'),
('fr', 'luxury_accommodation_desc', 'Découvrez le confort et l''élégance dans nos chambres magnifiquement conçues'),
('en', 'luxury_accommodation_desc', 'Experience comfort and elegance in our beautifully designed rooms'),
('fr', 'conference_facilities', 'Installations de conférence'),
('en', 'conference_facilities', 'Conference Facilities'),
('fr', 'conference_facilities_desc', 'Espaces de réunion professionnels équipés de technologie moderne'),
('en', 'conference_facilities_desc', 'Professional meeting spaces equipped with modern technology'),
('fr', 'fine_dining', 'Cuisine raffinée'),
('en', 'fine_dining', 'Fine Dining'),
('fr', 'fine_dining_desc', 'Cuisine exquise créée par notre équipe culinaire talentueuse'),
('en', 'fine_dining_desc', 'Exquisite cuisine crafted by our talented culinary team'),
('fr', 'featured_rooms', 'Chambres vedettes'),
('en', 'featured_rooms', 'Featured Rooms'),
('fr', 'guest_feedback', 'Commentaires des clients'),
('en', 'guest_feedback', 'Guest Feedback'),
('fr', 'no_feedback_available', 'Aucun commentaire client disponible pour le moment.'),
('en', 'no_feedback_available', 'No guest feedback available yet.'),

-- Dashboard translations
('fr', 'quick_actions', 'Actions rapides'),
('en', 'quick_actions', 'Quick Actions'),
('fr', 'common_management_tasks', 'Tâches de gestion communes'),
('en', 'common_management_tasks', 'Common management tasks'),
('fr', 'advanced_management', 'Gestion avancée'),
('en', 'advanced_management', 'Advanced Management'),
('fr', 'specialized_management_tools', 'Outils de gestion spécialisés'),
('en', 'specialized_management_tools', 'Specialized management tools'),

-- Admin dashboard stats
('fr', 'pending_payments', 'Paiements en attente'),
('en', 'pending_payments', 'Pending Payments'),
('fr', 'require_verification', 'Nécessitent vérification'),
('en', 'require_verification', 'Require verification'),
('fr', 'occupied_rooms', 'Chambres occupées'),
('en', 'occupied_rooms', 'Occupied Rooms'),
('fr', 'occupancy', 'occupation'),
('en', 'occupancy', 'occupancy'),
('fr', 'active_bookings', 'Réservations actives'),
('en', 'active_bookings', 'Active Bookings'),
('fr', 'current_future_bookings', 'Réservations actuelles et futures'),
('en', 'current_future_bookings', 'Current and future bookings'),
('fr', 'revenue_today', 'Chiffre d''affaires aujourd''hui'),
('en', 'revenue_today', 'Revenue Today'),
('fr', 'todays_completed_payments', 'Paiements complétés aujourd''hui'),
('en', 'todays_completed_payments', 'Today''s completed payments'),

-- Action buttons
('fr', 'manage_users', 'Gérer les utilisateurs'),
('en', 'manage_users', 'Manage Users'),
('fr', 'manage_rooms', 'Gérer les chambres'),
('en', 'manage_rooms', 'Manage Rooms'),
('fr', 'view_bookings', 'Voir les réservations'),
('en', 'view_bookings', 'View Bookings'),
('fr', 'analytics', 'Analyses'),
('en', 'analytics', 'Analytics'),
('fr', 'conference_rooms', 'Salles de conférence'),
('en', 'conference_rooms', 'Conference Rooms'),
('fr', 'menu_management', 'Gestion du menu'),
('en', 'menu_management', 'Menu Management'),
('fr', 'payment_verification', 'Vérification des paiements'),
('en', 'payment_verification', 'Payment Verification'),
('fr', 'content_management', 'Gestion du contenu'),
('en', 'content_management', 'Content Management')

ON CONFLICT (language, key) DO UPDATE SET 
value = EXCLUDED.value,
updated_at = now();