create table public.buffet_options (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10, 2) not null,
  is_available boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies
alter table public.buffet_options enable row level security;

create policy "Allow public read access"
  on public.buffet_options for select
  using (true);

create policy "Allow admin write access"
  on public.buffet_options for all
  using (get_current_user_role() = ANY (ARRAY['Admin'::app_role, 'SuperAdmin'::app_role]));

