// This file is automatically generated. Do not edit it directly.
// MODIFIED by Assistant to support Next.js SSR with @supabase/ssr
import { createClient as createSsrClient } from '@/utils/supabase/client';

// Exporting the singleton instance to maintain compatibility with existing imports
export const supabase = createSsrClient();
